rem inkscape --export-type=png --export-dpi=96 --export-filename=annotation_close.png annotation_close.svg
rem inkscape --export-type=png --export-dpi=192 --export-filename=annotation_close@2x.png annotation_close.svg
rem inkscape --export-type=png --export-dpi=288 --export-filename=annotation_close@3x.png annotation_close.svg
rem inkscape --export-type=png --export-dpi=96 --export-filename=autocomplete_detail.png autocomplete_detail.svg
rem inkscape --export-type=png --export-dpi=192 --export-filename=autocomplete_detail@2x.png autocomplete_detail.svg
rem inkscape --export-type=png --export-dpi=288 --export-filename=autocomplete_detail@3x.png autocomplete_detail.svg
rem inkscape --export-type=png --export-dpi=96 --export-filename=autocomplete_detail_winui.png autocomplete_detail_winui.svg
rem inkscape --export-type=png --export-dpi=192 --export-filename=autocomplete_detail_winui@2x.png autocomplete_detail_winui.svg
rem inkscape --export-type=png --export-dpi=288 --export-filename=autocomplete_detail_winui@3x.png autocomplete_detail_winui.svg
rem inkscape --export-type=png --export-dpi=96 --export-filename=background_2px.png background_2px.svg
rem inkscape --export-type=png --export-dpi=192 --export-filename=background_2px@2x.png background_2px.svg
rem inkscape --export-type=png --export-dpi=288 --export-filename=background_2px@3x.png background_2px.svg
rem inkscape --export-type=png --export-dpi=96 --export-filename=background_4px.png background_4px.svg
rem inkscape --export-type=png --export-dpi=192 --export-filename=background_4px@2x.png background_4px.svg
rem inkscape --export-type=png --export-dpi=288 --export-filename=background_4px@3x.png background_4px.svg
rem inkscape --export-type=png --export-dpi=96 --export-filename=background_4px_padding.png background_4px_padding.svg
rem inkscape --export-type=png --export-dpi=192 --export-filename=background_4px_padding@2x.png background_4px_padding.svg
rem inkscape --export-type=png --export-dpi=288 --export-filename=background_4px_padding@3x.png background_4px_padding.svg
rem inkscape --export-type=png --export-dpi=96 --export-filename=background_8px.png background_8px.svg
rem inkscape --export-type=png --export-dpi=192 --export-filename=background_8px@2x.png background_8px.svg
rem inkscape --export-type=png --export-dpi=288 --export-filename=background_8px@3x.png background_8px.svg
rem inkscape --export-type=png --export-dpi=96 --export-filename=border_2px.png border_2px.svg
rem inkscape --export-type=png --export-dpi=192 --export-filename=border_2px@2x.png border_2px.svg
rem inkscape --export-type=png --export-dpi=288 --export-filename=border_2px@3x.png border_2px.svg
rem inkscape --export-type=png --export-dpi=96 --export-filename=border_4px.png border_4px.svg
rem inkscape --export-type=png --export-dpi=192 --export-filename=border_4px@2x.png border_4px.svg
rem inkscape --export-type=png --export-dpi=288 --export-filename=border_4px@3x.png border_4px.svg
rem inkscape --export-type=png --export-dpi=96 --export-filename=border_8px.png border_8px.svg
rem inkscape --export-type=png --export-dpi=192 --export-filename=border_8px@2x.png border_8px.svg
rem inkscape --export-type=png --export-dpi=288 --export-filename=border_8px@3x.png border_8px.svg
rem inkscape --export-type=png --export-dpi=96 --export-filename=branch.png branch.svg
rem inkscape --export-type=png --export-dpi=192 --export-filename=branch@2x.png branch.svg
rem inkscape --export-type=png --export-dpi=288 --export-filename=branch@3x.png branch.svg
rem inkscape --export-type=png --export-dpi=96 --export-filename=button_background_r5.png button_background_r5.svg
rem inkscape --export-type=png --export-dpi=192 --export-filename=button_background_r5@2x.png button_background_r5.svg
rem inkscape --export-type=png --export-dpi=288 --export-filename=button_background_r5@3x.png button_background_r5.svg
rem inkscape --export-type=png --export-dpi=96 --export-filename=button_border_r5.png button_border_r5.svg
rem inkscape --export-type=png --export-dpi=192 --export-filename=button_border_r5@2x.png button_border_r5.svg
rem inkscape --export-type=png --export-dpi=288 --export-filename=button_border_r5@3x.png button_border_r5.svg
rem inkscape --export-type=png --export-dpi=96 --export-filename=button_background_left.png button_background_left.svg
rem inkscape --export-type=png --export-dpi=192 --export-filename=button_background_left@2x.png button_background_left.svg
rem inkscape --export-type=png --export-dpi=288 --export-filename=button_background_left@3x.png button_background_left.svg
rem inkscape --export-type=png --export-dpi=96 --export-filename=button_background_right.png button_background_right.svg
rem inkscape --export-type=png --export-dpi=192 --export-filename=button_background_right@2x.png button_background_right.svg
rem inkscape --export-type=png --export-dpi=288 --export-filename=button_background_right@3x.png button_background_right.svg
rem inkscape --export-type=png --export-dpi=96 --export-filename=button_border_center.png button_border_center.svg
rem inkscape --export-type=png --export-dpi=192 --export-filename=button_border_center@2x.png button_border_center@2x.svg
rem inkscape --export-type=png --export-dpi=96 --export-filename=button_border_left.png button_border_left.svg
rem inkscape --export-type=png --export-dpi=192 --export-filename=button_border_left@2x.png button_border_left@2x.svg
rem inkscape --export-type=png --export-dpi=96 --export-filename=button_border_right.png button_border_right.svg
rem inkscape --export-type=png --export-dpi=192 --export-filename=button_border_right@2x.png button_border_right@2x.svg
rem inkscape --export-type=png --export-dpi=96 --export-filename=checkbox14_background.png checkbox14_background.svg
rem inkscape --export-type=png --export-dpi=192 --export-filename=checkbox14_background@2x.png checkbox14_background.svg
rem inkscape --export-type=png --export-dpi=288 --export-filename=checkbox14_background@3x.png checkbox14_background.svg
rem inkscape --export-type=png --export-dpi=96 --export-filename=checkbox14_border.png checkbox14_border.svg
rem inkscape --export-type=png --export-dpi=192 --export-filename=checkbox14_border@2x.png checkbox14_border.svg
rem inkscape --export-type=png --export-dpi=288 --export-filename=checkbox14_border@3x.png checkbox14_border.svg
rem inkscape --export-type=png --export-dpi=96 --export-filename=checkbox14_checked.png checkbox14_checked.svg
rem inkscape --export-type=png --export-dpi=192 --export-filename=checkbox14_checked@2x.png checkbox14_checked.svg
rem inkscape --export-type=png --export-dpi=288 --export-filename=checkbox14_checked@3x.png checkbox14_checked.svg
rem inkscape --export-type=png --export-dpi=96 --export-filename=checkbox14_checked_alt.png checkbox14_checked_alt.svg
rem inkscape --export-type=png --export-dpi=192 --export-filename=checkbox14_checked_alt@2x.png checkbox14_checked_alt.svg
rem inkscape --export-type=png --export-dpi=288 --export-filename=checkbox14_checked_alt@3x.png checkbox14_checked_alt.svg
rem inkscape --export-type=png --export-dpi=96 --export-filename=checkbox14_checkmark.png checkbox14_checkmark.svg
rem inkscape --export-type=png --export-dpi=192 --export-filename=checkbox14_checkmark@2x.png checkbox14_checkmark.svg
rem inkscape --export-type=png --export-dpi=288 --export-filename=checkbox14_checkmark@3x.png checkbox14_checkmark.svg
rem inkscape --export-type=png --export-dpi=96 --export-filename=checkbox14_filled.png checkbox14_filled.svg
rem inkscape --export-type=png --export-dpi=192 --export-filename=checkbox14_filled@2x.png checkbox14_filled.svg
rem inkscape --export-type=png --export-dpi=288 --export-filename=checkbox14_filled@3x.png checkbox14_filled.svg
rem inkscape --export-type=png --export-dpi=96 --export-filename=checkbox18_border.png checkbox18_border.svg
rem inkscape --export-type=png --export-dpi=192 --export-filename=checkbox18_border@2x.png checkbox18_border.svg
rem inkscape --export-type=png --export-dpi=288 --export-filename=checkbox18_border@3x.png checkbox18_border.svg
rem inkscape --export-type=png --export-dpi=96 --export-filename=toggle_background.png toggle_background.svg
rem inkscape --export-type=png --export-dpi=192 --export-filename=toggle_background@2x.png toggle_background.svg
rem inkscape --export-type=png --export-dpi=288 --export-filename=toggle_background@3x.png toggle_background.svg
rem inkscape --export-type=png --export-dpi=96 --export-filename=toggle_border.png toggle_border.svg
rem inkscape --export-type=png --export-dpi=192 --export-filename=toggle_border@2x.png toggle_border.svg
rem inkscape --export-type=png --export-dpi=288 --export-filename=toggle_border@3x.png toggle_border.svg
rem inkscape --export-type=png --export-dpi=96 --export-filename=toggle_knob.png toggle_knob.svg
rem inkscape --export-type=png --export-dpi=192 --export-filename=toggle_knob@2x.png toggle_knob.svg
rem inkscape --export-type=png --export-dpi=288 --export-filename=toggle_knob@3x.png toggle_knob.svg
rem inkscape --export-type=png --export-dpi=96 --export-filename=input_border.png input_border.svg
rem inkscape --export-type=png --export-dpi=192 --export-filename=input_border@2x.png input_border.svg
rem inkscape --export-type=png --export-dpi=288 --export-filename=input_border@3x.png input_border.svg
rem inkscape --export-type=png --export-dpi=96 --export-filename=input_border2.png input_border2.svg
rem inkscape --export-type=png --export-dpi=192 --export-filename=input_border2@2x.png input_border2.svg
rem inkscape --export-type=png --export-dpi=288 --export-filename=input_border2@3x.png input_border2.svg
rem inkscape --export-type=png --export-dpi=96 --export-filename=input_border_focus.png input_border_focus.svg
rem inkscape --export-type=png --export-dpi=192 --export-filename=input_border_focus@2x.png input_border_focus.svg
rem inkscape --export-type=png --export-dpi=288 --export-filename=input_border_focus@3x.png input_border_focus.svg
rem inkscape --export-type=png --export-dpi=96 --export-filename=close.png close.svg
rem inkscape --export-type=png --export-dpi=192 --export-filename=close@2x.png close.svg
rem inkscape --export-type=png --export-dpi=288 --export-filename=close@3x.png close.svg
rem inkscape --export-type=png --export-dpi=96 --export-filename=console_input_background.png console_input_background.svg
rem inkscape --export-type=png --export-dpi=192 --export-filename=console_input_background@2x.png console_input_background.svg
rem inkscape --export-type=png --export-dpi=288 --export-filename=console_input_background@3x.png console_input_background.svg
rem inkscape --export-type=png --export-dpi=96 --export-filename=console_input_border.png console_input_border.svg
rem inkscape --export-type=png --export-dpi=192 --export-filename=console_input_border@2x.png console_input_border.svg
rem inkscape --export-type=png --export-dpi=288 --export-filename=console_input_border@3x.png console_input_border.svg
rem inkscape --export-type=png --export-dpi=96 --export-filename=disclosure_expanded.png disclosure_expanded.svg
rem inkscape --export-type=png --export-dpi=192 --export-filename=disclosure_expanded@2x.png disclosure_expanded.svg
rem inkscape --export-type=png --export-dpi=288 --export-filename=disclosure_expanded@3x.png disclosure_expanded.svg
rem inkscape --export-type=png --export-dpi=96 --export-filename=disclosure_expanded_shadow.png disclosure_expanded_shadow.svg
rem inkscape --export-type=png --export-dpi=192 --export-filename=disclosure_expanded_shadow@2x.png disclosure_expanded_shadow.svg
rem inkscape --export-type=png --export-dpi=288 --export-filename=disclosure_expanded_shadow@3x.png disclosure_expanded_shadow.svg
rem inkscape --export-type=png --export-dpi=96 --export-filename=disclosure_unexpanded.png disclosure_unexpanded.svg
rem inkscape --export-type=png --export-dpi=192 --export-filename=disclosure_unexpanded@2x.png disclosure_unexpanded.svg
rem inkscape --export-type=png --export-dpi=288 --export-filename=disclosure_unexpanded@3x.png disclosure_unexpanded.svg
rem inkscape --export-type=png --export-dpi=96 --export-filename=disclosure_unexpanded_shadow.png disclosure_unexpanded_shadow.svg
rem inkscape --export-type=png --export-dpi=192 --export-filename=disclosure_unexpanded_shadow@2x.png disclosure_unexpanded_shadow.svg
rem inkscape --export-type=png --export-dpi=288 --export-filename=disclosure_unexpanded_shadow@3x.png disclosure_unexpanded_shadow.svg
rem inkscape --export-type=png --export-dpi=96 --export-filename=dropdown.png dropdown.svg
rem inkscape --export-type=png --export-dpi=192 --export-filename=dropdown@2x.png dropdown.svg
rem inkscape --export-type=png --export-dpi=288 --export-filename=dropdown@3x.png dropdown.svg
rem inkscape --export-type=png --export-dpi=96 --export-filename=history.png history.svg
rem inkscape --export-type=png --export-dpi=192 --export-filename=history@2x.png history.svg
rem inkscape --export-type=png --export-dpi=288 --export-filename=history@3x.png history.svg
rem inkscape --export-type=png --export-dpi=96 --export-filename=icon_case_sensitive.png icon_case_sensitive.svg
rem inkscape --export-type=png --export-dpi=192 --export-filename=icon_case_sensitive@2x.png icon_case_sensitive.svg
rem inkscape --export-type=png --export-dpi=288 --export-filename=icon_case_sensitive@3x.png icon_case_sensitive.svg
rem inkscape --export-type=png --export-dpi=96 --export-filename=icon_regex.png icon_regex.svg
rem inkscape --export-type=png --export-dpi=192 --export-filename=icon_regex@2x.png icon_regex.svg
rem inkscape --export-type=png --export-dpi=288 --export-filename=icon_regex@3x.png icon_regex.svg
rem inkscape --export-type=png --export-dpi=96 --export-filename=overlay_background.png overlay_background.svg
rem inkscape --export-type=png --export-dpi=192 --export-filename=overlay_background@2x.png overlay_background.svg
rem inkscape --export-type=png --export-dpi=288 --export-filename=overlay_background@3x.png overlay_background.svg
rem inkscape --export-type=png --export-dpi=96 --export-filename=output_panel_border.png output_panel_border.svg
rem inkscape --export-type=png --export-dpi=192 --export-filename=output_panel_border@2x.png output_panel_border.svg
rem inkscape --export-type=png --export-dpi=288 --export-filename=output_panel_border@3x.png output_panel_border.svg
rem inkscape --export-type=png --export-dpi=96 --export-filename=overlay_border.png overlay_border.svg
rem inkscape --export-type=png --export-dpi=192 --export-filename=overlay_border@2x.png overlay_border.svg
rem inkscape --export-type=png --export-dpi=288 --export-filename=overlay_border@3x.png overlay_border.svg
rem inkscape --export-type=png --export-dpi=96 --export-filename=overlay_shadow.png overlay_shadow.svg
rem inkscape --export-type=png --export-dpi=192 --export-filename=overlay_shadow@2x.png overlay_shadow.svg
rem inkscape --export-type=png --export-dpi=288 --export-filename=overlay_shadow@3x.png overlay_shadow.svg
rem inkscape --export-type=png --export-dpi=96 --export-filename=popup_background.png popup_background.svg
rem inkscape --export-type=png --export-dpi=192 --export-filename=popup_background@2x.png popup_background.svg
rem inkscape --export-type=png --export-dpi=288 --export-filename=popup_background@3x.png popup_background.svg
rem inkscape --export-type=png --export-dpi=96 --export-filename=popup_border.png popup_border.svg
rem inkscape --export-type=png --export-dpi=192 --export-filename=popup_border@2x.png popup_border.svg
rem inkscape --export-type=png --export-dpi=288 --export-filename=popup_border@3x.png popup_border.svg
rem inkscape --export-type=png --export-dpi=96 --export-filename=tooltip_background.png tooltip_background.svg
rem inkscape --export-type=png --export-dpi=192 --export-filename=tooltip_background@2x.png tooltip_background.svg
rem inkscape --export-type=png --export-dpi=288 --export-filename=tooltip_background@3x.png tooltip_background.svg
rem inkscape --export-type=png --export-dpi=96 --export-filename=tooltip_border.png tooltip_border.svg
rem inkscape --export-type=png --export-dpi=192 --export-filename=tooltip_border@2x.png tooltip_border.svg
rem inkscape --export-type=png --export-dpi=288 --export-filename=tooltip_border@3x.png tooltip_border.svg
rem inkscape --export-type=png --export-dpi=96 --export-filename=tooltip_shadow.png tooltip_shadow.svg
rem inkscape --export-type=png --export-dpi=192 --export-filename=tooltip_shadow@2x.png tooltip_shadow.svg
rem inkscape --export-type=png --export-dpi=288 --export-filename=tooltip_shadow@3x.png tooltip_shadow.svg
rem inkscape --export-type=png --export-dpi=96 --export-filename=scroll.png scroll.svg
rem inkscape --export-type=png --export-dpi=192 --export-filename=scroll@2x.png scroll.svg
rem inkscape --export-type=png --export-dpi=288 --export-filename=scroll@3x.png scroll.svg
rem inkscape --export-type=png --export-dpi=96 --export-filename=scroll2.png scroll2.svg
rem inkscape --export-type=png --export-dpi=192 --export-filename=scroll2@2x.png scroll2.svg
rem inkscape --export-type=png --export-dpi=288 --export-filename=scroll2@3x.png scroll2.svg
rem inkscape --export-type=png --export-dpi=96 --export-filename=scroll3.png scroll3.svg
rem inkscape --export-type=png --export-dpi=192 --export-filename=scroll3@2x.png scroll3.svg
rem inkscape --export-type=png --export-dpi=288 --export-filename=scroll3@3x.png scroll3.svg
rem inkscape --export-type=png --export-dpi=96 --export-filename=scroll_horiz.png scroll_horiz.svg
rem inkscape --export-type=png --export-dpi=192 --export-filename=scroll_horiz@2x.png scroll_horiz.svg
rem inkscape --export-type=png --export-dpi=288 --export-filename=scroll_horiz@3x.png scroll_horiz.svg
rem inkscape --export-type=png --export-dpi=96 --export-filename=scroll_horiz2.png scroll_horiz2.svg
rem inkscape --export-type=png --export-dpi=192 --export-filename=scroll_horiz2@2x.png scroll_horiz2.svg
rem inkscape --export-type=png --export-dpi=288 --export-filename=scroll_horiz2@3x.png scroll_horiz2.svg
rem inkscape --export-type=png --export-dpi=96 --export-filename=scroll_horiz3.png scroll_horiz3.svg
rem inkscape --export-type=png --export-dpi=192 --export-filename=scroll_horiz3@2x.png scroll_horiz3.svg
rem inkscape --export-type=png --export-dpi=288 --export-filename=scroll_horiz3@3x.png scroll_horiz3.svg
rem inkscape --export-type=png --export-dpi=96 --export-filename=scroll_autocomplete_background.png scroll_autocomplete_background.svg
rem inkscape --export-type=png --export-dpi=192 --export-filename=scroll_autocomplete_background@2x.png scroll_autocomplete_background.svg
rem inkscape --export-type=png --export-dpi=288 --export-filename=scroll_autocomplete_background@3x.png scroll_autocomplete_background.svg
rem inkscape --export-type=png --export-dpi=96 --export-filename=sidebar_angled_background.png sidebar_angled_background.svg
rem inkscape --export-type=png --export-dpi=192 --export-filename=sidebar_angled_background@2x.png sidebar_angled_background.svg
rem inkscape --export-type=png --export-dpi=288 --export-filename=sidebar_angled_background@3x.png sidebar_angled_background.svg
rem inkscape --export-type=png --export-dpi=96 --export-filename=sidebar_angled_border.png sidebar_angled_border.svg
rem inkscape --export-type=png --export-dpi=192 --export-filename=sidebar_angled_border@2x.png sidebar_angled_border.svg
rem inkscape --export-type=png --export-dpi=288 --export-filename=sidebar_angled_border@3x.png sidebar_angled_border.svg
rem inkscape --export-type=png --export-dpi=96 --export-filename=sidebar_rounded_background.png sidebar_rounded_background.svg
rem inkscape --export-type=png --export-dpi=192 --export-filename=sidebar_rounded_background@2x.png sidebar_rounded_background.svg
rem inkscape --export-type=png --export-dpi=288 --export-filename=sidebar_rounded_background@3x.png sidebar_rounded_background.svg
rem inkscape --export-type=png --export-dpi=96 --export-filename=sidebar_rounded_border.png sidebar_rounded_border.svg
rem inkscape --export-type=png --export-dpi=192 --export-filename=sidebar_rounded_border@2x.png sidebar_rounded_border.svg
rem inkscape --export-type=png --export-dpi=288 --export-filename=sidebar_rounded_border@3x.png sidebar_rounded_border.svg
rem inkscape --export-type=png --export-dpi=96 --export-filename=sidebar_square_background.png sidebar_square_background.svg
rem inkscape --export-type=png --export-dpi=192 --export-filename=sidebar_square_background@2x.png sidebar_square_background.svg
rem inkscape --export-type=png --export-dpi=288 --export-filename=sidebar_square_background@3x.png sidebar_square_background.svg
rem inkscape --export-type=png --export-dpi=96 --export-filename=sidebar_square_border.png sidebar_square_border.svg
rem inkscape --export-type=png --export-dpi=192 --export-filename=sidebar_square_border@2x.png sidebar_square_border.svg
rem inkscape --export-type=png --export-dpi=288 --export-filename=sidebar_square_border@3x.png sidebar_square_border.svg
rem inkscape --export-type=png --export-dpi=96 --export-filename=sidebar_winui_background.png sidebar_winui_background.svg
rem inkscape --export-type=png --export-dpi=192 --export-filename=sidebar_winui_background@2x.png sidebar_winui_background.svg
rem inkscape --export-type=png --export-dpi=288 --export-filename=sidebar_winui_background@3x.png sidebar_winui_background.svg
rem inkscape --export-type=png --export-dpi=96 --export-filename=sidebar_winui_border.png sidebar_winui_border.svg
rem inkscape --export-type=png --export-dpi=192 --export-filename=sidebar_winui_border@2x.png sidebar_winui_border.svg
rem inkscape --export-type=png --export-dpi=288 --export-filename=sidebar_winui_border@3x.png sidebar_winui_border.svg
rem inkscape --export-type=png --export-dpi=96 --export-filename=sidebar_row_selected.png sidebar_row_selected.svg
rem inkscape --export-type=png --export-dpi=192 --export-filename=sidebar_row_selected@2x.png sidebar_row_selected.svg
rem inkscape --export-type=png --export-dpi=288 --export-filename=sidebar_row_selected@3x.png sidebar_row_selected.svg
rem inkscape --export-type=png --export-dpi=96 --export-filename=sidebar_row_selected_border.png sidebar_row_selected_border.svg
rem inkscape --export-type=png --export-dpi=192 --export-filename=sidebar_row_selected_border@2x.png sidebar_row_selected_border.svg
rem inkscape --export-type=png --export-dpi=288 --export-filename=sidebar_row_selected_border@3x.png sidebar_row_selected_border.svg
rem inkscape --export-type=png --export-dpi=96 --export-filename=sidebar_row_selected_winui.png sidebar_row_selected_winui.svg
rem inkscape --export-type=png --export-dpi=192 --export-filename=sidebar_row_selected_winui@2x.png sidebar_row_selected_winui.svg
rem inkscape --export-type=png --export-dpi=288 --export-filename=sidebar_row_selected_winui@3x.png sidebar_row_selected_winui.svg
rem inkscape --export-type=png --export-dpi=96 --export-filename=sidebar_row_selected_border_winui.png sidebar_row_selected_border_winui.svg
rem inkscape --export-type=png --export-dpi=192 --export-filename=sidebar_row_selected_border_winui@2x.png sidebar_row_selected_border_winui.svg
rem inkscape --export-type=png --export-dpi=288 --export-filename=sidebar_row_selected_border_winui@3x.png sidebar_row_selected_border_winui.svg
rem inkscape --export-type=png --export-dpi=96 --export-filename=tab_scroll_left.png tab_scroll_left.svg
rem inkscape --export-type=png --export-dpi=192 --export-filename=tab_scroll_left@2x.png tab_scroll_left.svg
rem inkscape --export-type=png --export-dpi=288 --export-filename=tab_scroll_left@3x.png tab_scroll_left.svg
rem inkscape --export-type=png --export-dpi=96 --export-filename=tab_scroll_right.png tab_scroll_right.svg
rem inkscape --export-type=png --export-dpi=192 --export-filename=tab_scroll_right@2x.png tab_scroll_right.svg
rem inkscape --export-type=png --export-dpi=288 --export-filename=tab_scroll_right@3x.png tab_scroll_right.svg
rem inkscape --export-type=png --export-dpi=96 --export-filename=tabset_border.png tabset_border.svg
rem inkscape --export-type=png --export-dpi=192 --export-filename=tabset_border@2x.png tabset_border.svg
rem inkscape --export-type=png --export-dpi=288 --export-filename=tabset_border@3x.png tabset_border.svg
rem inkscape --export-type=png --export-dpi=96 --export-filename=tabset_shadow.png tabset_shadow.svg
rem inkscape --export-type=png --export-dpi=192 --export-filename=tabset_shadow@2x.png tabset_shadow.svg
rem inkscape --export-type=png --export-dpi=288 --export-filename=tabset_shadow@3x.png tabset_shadow.svg
rem inkscape --export-type=png --export-dpi=96 --export-filename=tab_dirty.png tab_dirty.svg
rem inkscape --export-type=png --export-dpi=192 --export-filename=tab_dirty@2x.png tab_dirty.svg
rem inkscape --export-type=png --export-dpi=288 --export-filename=tab_dirty@3x.png tab_dirty.svg
rem inkscape --export-type=png --export-dpi=96 --export-filename=tab_connector_left_overhang.png tab_connector_left_overhang.svg
rem inkscape --export-type=png --export-dpi=192 --export-filename=tab_connector_left_overhang@2x.png tab_connector_left_overhang.svg
rem inkscape --export-type=png --export-dpi=288 --export-filename=tab_connector_left_overhang@3x.png tab_connector_left_overhang.svg
rem inkscape --export-type=png --export-dpi=96 --export-filename=tab_connector_right_overhang.png tab_connector_right_overhang.svg
rem inkscape --export-type=png --export-dpi=192 --export-filename=tab_connector_right_overhang@2x.png tab_connector_right_overhang.svg
rem inkscape --export-type=png --export-dpi=288 --export-filename=tab_connector_right_overhang@3x.png tab_connector_right_overhang.svg
rem inkscape --export-type=png --export-dpi=96 --export-filename=tab_connector_left_overhang2.png tab_connector_left_overhang2.svg
rem inkscape --export-type=png --export-dpi=192 --export-filename=tab_connector_left_overhang2@2x.png tab_connector_left_overhang2.svg
rem inkscape --export-type=png --export-dpi=288 --export-filename=tab_connector_left_overhang2@3x.png tab_connector_left_overhang2.svg
rem inkscape --export-type=png --export-dpi=96 --export-filename=tab_connector_right_overhang2.png tab_connector_right_overhang2.svg
rem inkscape --export-type=png --export-dpi=192 --export-filename=tab_connector_right_overhang2@2x.png tab_connector_right_overhang2.svg
rem inkscape --export-type=png --export-dpi=288 --export-filename=tab_connector_right_overhang2@3x.png tab_connector_right_overhang2.svg
rem inkscape --export-type=png --export-dpi=96 --export-filename=tab_border_bottom.png tab_border_bottom.svg
rem inkscape --export-type=png --export-dpi=192 --export-filename=tab_border_bottom@2x.png tab_border_bottom.svg
rem inkscape --export-type=png --export-dpi=288 --export-filename=tab_border_bottom@3x.png tab_border_bottom.svg
rem inkscape --export-type=png --export-dpi=96 --export-filename=tab_rounded.png tab_rounded.svg
rem inkscape --export-type=png --export-dpi=192 --export-filename=tab_rounded@2x.png tab_rounded.svg
rem inkscape --export-type=png --export-dpi=288 --export-filename=tab_rounded@3x.png tab_rounded.svg
rem inkscape --export-type=png --export-dpi=96 --export-filename=tab_rounded_border.png tab_rounded_border.svg
rem inkscape --export-type=png --export-dpi=192 --export-filename=tab_rounded_border@2x.png tab_rounded_border.svg
rem inkscape --export-type=png --export-dpi=288 --export-filename=tab_rounded_border@3x.png tab_rounded_border.svg
rem inkscape --export-type=png --export-dpi=96 --export-filename=tab_rounded_border2.png tab_rounded_border2.svg
rem inkscape --export-type=png --export-dpi=192 --export-filename=tab_rounded_border2@2x.png tab_rounded_border2.svg
rem inkscape --export-type=png --export-dpi=288 --export-filename=tab_rounded_border2@3x.png tab_rounded_border2.svg
rem inkscape --export-type=png --export-dpi=96 --export-filename=tab_rounded_border3.png tab_rounded_border3.svg
rem inkscape --export-type=png --export-dpi=192 --export-filename=tab_rounded_border3@2x.png tab_rounded_border3.svg
rem inkscape --export-type=png --export-dpi=288 --export-filename=tab_rounded_border3@3x.png tab_rounded_border3.svg
rem inkscape --export-type=png --export-dpi=96 --export-filename=tab_rounded_border4.png tab_rounded_border4.svg
rem inkscape --export-type=png --export-dpi=192 --export-filename=tab_rounded_border4@2x.png tab_rounded_border4.svg
rem inkscape --export-type=png --export-dpi=288 --export-filename=tab_rounded_border4@3x.png tab_rounded_border4.svg
rem inkscape --export-type=png --export-dpi=96 --export-filename=tab_rounded_border5.png tab_rounded_border5.svg
rem inkscape --export-type=png --export-dpi=192 --export-filename=tab_rounded_border5@2x.png tab_rounded_border5.svg
rem inkscape --export-type=png --export-dpi=288 --export-filename=tab_rounded_border5@3x.png tab_rounded_border5.svg
rem inkscape --export-type=png --export-dpi=96 --export-filename=tab_rounded_shadow.png tab_rounded_shadow.svg
rem inkscape --export-type=png --export-dpi=192 --export-filename=tab_rounded_shadow@2x.png tab_rounded_shadow.svg
rem inkscape --export-type=png --export-dpi=288 --export-filename=tab_rounded_shadow@3x.png tab_rounded_shadow.svg
rem inkscape --export-type=png --export-dpi=96 --export-filename=tab_rounded_shadow2.png tab_rounded_shadow2.svg
rem inkscape --export-type=png --export-dpi=192 --export-filename=tab_rounded_shadow2@2x.png tab_rounded_shadow2.svg
rem inkscape --export-type=png --export-dpi=288 --export-filename=tab_rounded_shadow2@3x.png tab_rounded_shadow2.svg
rem inkscape --export-type=png --export-dpi=96 --export-filename=tab_rounded_shadow3.png tab_rounded_shadow3.svg
rem inkscape --export-type=png --export-dpi=192 --export-filename=tab_rounded_shadow3@2x.png tab_rounded_shadow3.svg
rem inkscape --export-type=png --export-dpi=288 --export-filename=tab_rounded_shadow3@3x.png tab_rounded_shadow3.svg
rem inkscape --export-type=png --export-dpi=96 --export-filename=tab_rounded_shadow4.png tab_rounded_shadow4.svg
rem inkscape --export-type=png --export-dpi=192 --export-filename=tab_rounded_shadow4@2x.png tab_rounded_shadow4.svg
rem inkscape --export-type=png --export-dpi=288 --export-filename=tab_rounded_shadow4@3x.png tab_rounded_shadow4.svg
rem inkscape --export-type=png --export-dpi=96 --export-filename=tab_rounded_shadow5.png tab_rounded_shadow5.svg
rem inkscape --export-type=png --export-dpi=192 --export-filename=tab_rounded_shadow5@2x.png tab_rounded_shadow5.svg
rem inkscape --export-type=png --export-dpi=288 --export-filename=tab_rounded_shadow5@3x.png tab_rounded_shadow5.svg
rem inkscape --export-type=png --export-dpi=96 --export-filename=tab_rounded_shadow6.png tab_rounded_shadow6.svg
rem inkscape --export-type=png --export-dpi=192 --export-filename=tab_rounded_shadow6@2x.png tab_rounded_shadow6.svg
rem inkscape --export-type=png --export-dpi=288 --export-filename=tab_rounded_shadow6@3x.png tab_rounded_shadow6.svg
rem inkscape --export-type=png --export-dpi=96 --export-filename=tab_rounded_shadow7.png tab_rounded_shadow7.svg
rem inkscape --export-type=png --export-dpi=192 --export-filename=tab_rounded_shadow7@2x.png tab_rounded_shadow7.svg
rem inkscape --export-type=png --export-dpi=288 --export-filename=tab_rounded_shadow7@3x.png tab_rounded_shadow7.svg
rem inkscape --export-type=png --export-dpi=96 --export-filename=tab_rounded_shadow8.png tab_rounded_shadow8.svg
rem inkscape --export-type=png --export-dpi=192 --export-filename=tab_rounded_shadow8@2x.png tab_rounded_shadow8.svg
rem inkscape --export-type=png --export-dpi=288 --export-filename=tab_rounded_shadow8@3x.png tab_rounded_shadow8.svg
rem inkscape --export-type=png --export-dpi=96 --export-filename=tab_rounded_highlight.png tab_rounded_highlight.svg
rem inkscape --export-type=png --export-dpi=192 --export-filename=tab_rounded_highlight@2x.png tab_rounded_highlight.svg
rem inkscape --export-type=png --export-dpi=288 --export-filename=tab_rounded_highlight@3x.png tab_rounded_highlight.svg
rem inkscape --export-type=png --export-dpi=96 --export-filename=tab_rounded_highlight2.png tab_rounded_highlight2.svg
rem inkscape --export-type=png --export-dpi=192 --export-filename=tab_rounded_highlight2@2x.png tab_rounded_highlight2.svg
rem inkscape --export-type=png --export-dpi=288 --export-filename=tab_rounded_highlight2@3x.png tab_rounded_highlight2.svg
rem inkscape --export-type=png --export-dpi=96 --export-filename=tab_rounded_highlight3.png tab_rounded_highlight3.svg
rem inkscape --export-type=png --export-dpi=192 --export-filename=tab_rounded_highlight3@2x.png tab_rounded_highlight3.svg
rem inkscape --export-type=png --export-dpi=288 --export-filename=tab_rounded_highlight3@3x.png tab_rounded_highlight3.svg
rem inkscape --export-type=png --export-dpi=96 --export-filename=tab_rounded_highlight4.png tab_rounded_highlight4.svg
rem inkscape --export-type=png --export-dpi=192 --export-filename=tab_rounded_highlight4@2x.png tab_rounded_highlight4.svg
rem inkscape --export-type=png --export-dpi=288 --export-filename=tab_rounded_highlight4@3x.png tab_rounded_highlight4.svg
rem inkscape --export-type=png --export-dpi=96 --export-filename=tab_rounded_divider.png tab_rounded_divider.svg
rem inkscape --export-type=png --export-dpi=192 --export-filename=tab_rounded_divider@2x.png tab_rounded_divider.svg
rem inkscape --export-type=png --export-dpi=288 --export-filename=tab_rounded_divider@3x.png tab_rounded_divider.svg
rem inkscape --export-type=png --export-dpi=96 --export-filename=tab_square.png tab_square.svg
rem inkscape --export-type=png --export-dpi=192 --export-filename=tab_square@2x.png tab_square.svg
rem inkscape --export-type=png --export-dpi=288 --export-filename=tab_square@3x.png tab_square.svg
rem inkscape --export-type=png --export-dpi=96 --export-filename=tab_square2.png tab_square2.svg
rem inkscape --export-type=png --export-dpi=192 --export-filename=tab_square2@2x.png tab_square2.svg
rem inkscape --export-type=png --export-dpi=288 --export-filename=tab_square2@3x.png tab_square2.svg
rem inkscape --export-type=png --export-dpi=96 --export-filename=tab_square_border.png tab_square_border.svg
rem inkscape --export-type=png --export-dpi=192 --export-filename=tab_square_border@2x.png tab_square_border.svg
rem inkscape --export-type=png --export-dpi=288 --export-filename=tab_square_border@3x.png tab_square_border.svg
rem inkscape --export-type=png --export-dpi=96 --export-filename=tab_square_border2.png tab_square_border2.svg
rem inkscape --export-type=png --export-dpi=192 --export-filename=tab_square_border2@2x.png tab_square_border2.svg
rem inkscape --export-type=png --export-dpi=288 --export-filename=tab_square_border2@3x.png tab_square_border2.svg
rem inkscape --export-type=png --export-dpi=96 --export-filename=tab_square_shadow.png tab_square_shadow.svg
rem inkscape --export-type=png --export-dpi=192 --export-filename=tab_square_shadow@2x.png tab_square_shadow.svg
rem inkscape --export-type=png --export-dpi=288 --export-filename=tab_square_shadow@3x.png tab_square_shadow.svg
rem inkscape --export-type=png --export-dpi=96 --export-filename=tab_square_shadow2.png tab_square_shadow2.svg
rem inkscape --export-type=png --export-dpi=192 --export-filename=tab_square_shadow2@2x.png tab_square_shadow2.svg
rem inkscape --export-type=png --export-dpi=288 --export-filename=tab_square_shadow2@3x.png tab_square_shadow2.svg
rem inkscape --export-type=png --export-dpi=96 --export-filename=tab_square_highlight.png tab_square_highlight.svg
rem inkscape --export-type=png --export-dpi=192 --export-filename=tab_square_highlight@2x.png tab_square_highlight.svg
rem inkscape --export-type=png --export-dpi=288 --export-filename=tab_square_highlight@3x.png tab_square_highlight.svg
rem inkscape --export-type=png --export-dpi=96 --export-filename=tab_square_highlight2.png tab_square_highlight2.svg
rem inkscape --export-type=png --export-dpi=192 --export-filename=tab_square_highlight2@2x.png tab_square_highlight2.svg
rem inkscape --export-type=png --export-dpi=288 --export-filename=tab_square_highlight2@3x.png tab_square_highlight2.svg
rem inkscape --export-type=png --export-dpi=96 --export-filename=tab_square_highlight3.png tab_square_highlight3.svg
rem inkscape --export-type=png --export-dpi=192 --export-filename=tab_square_highlight3@2x.png tab_square_highlight3.svg
rem inkscape --export-type=png --export-dpi=288 --export-filename=tab_square_highlight3@3x.png tab_square_highlight3.svg
rem inkscape --export-type=png --export-dpi=96 --export-filename=tab_square_highlight4.png tab_square_highlight4.svg
rem inkscape --export-type=png --export-dpi=192 --export-filename=tab_square_highlight4@2x.png tab_square_highlight4.svg
rem inkscape --export-type=png --export-dpi=288 --export-filename=tab_square_highlight4@3x.png tab_square_highlight4.svg
rem inkscape --export-type=png --export-dpi=96 --export-filename=tab_square_divider.png tab_square_divider.svg
rem inkscape --export-type=png --export-dpi=192 --export-filename=tab_square_divider@2x.png tab_square_divider.svg
rem inkscape --export-type=png --export-dpi=288 --export-filename=tab_square_divider@3x.png tab_square_divider.svg
rem inkscape --export-type=png --export-dpi=96 --export-filename=tab_square_divider2.png tab_square_divider2.svg
rem inkscape --export-type=png --export-dpi=192 --export-filename=tab_square_divider2@2x.png tab_square_divider2.svg
rem inkscape --export-type=png --export-dpi=288 --export-filename=tab_square_divider2@3x.png tab_square_divider2.svg
rem inkscape --export-type=png --export-dpi=96 --export-filename=tab_angled.png tab_angled.svg
rem inkscape --export-type=png --export-dpi=192 --export-filename=tab_angled@2x.png tab_angled.svg
rem inkscape --export-type=png --export-dpi=288 --export-filename=tab_angled@3x.png tab_angled.svg
rem inkscape --export-type=png --export-dpi=96 --export-filename=tab_angled2.png tab_angled2.svg
rem inkscape --export-type=png --export-dpi=192 --export-filename=tab_angled2@2x.png tab_angled2.svg
rem inkscape --export-type=png --export-dpi=288 --export-filename=tab_angled2@3x.png tab_angled2.svg
rem inkscape --export-type=png --export-dpi=96 --export-filename=tab_angled_border.png tab_angled_border.svg
rem inkscape --export-type=png --export-dpi=192 --export-filename=tab_angled_border@2x.png tab_angled_border.svg
rem inkscape --export-type=png --export-dpi=288 --export-filename=tab_angled_border@3x.png tab_angled_border.svg
rem inkscape --export-type=png --export-dpi=96 --export-filename=tab_angled_border2.png tab_angled_border2.svg
rem inkscape --export-type=png --export-dpi=192 --export-filename=tab_angled_border2@2x.png tab_angled_border2.svg
rem inkscape --export-type=png --export-dpi=288 --export-filename=tab_angled_border2@3x.png tab_angled_border2.svg
rem inkscape --export-type=png --export-dpi=96 --export-filename=tab_angled_border3.png tab_angled_border3.svg
rem inkscape --export-type=png --export-dpi=192 --export-filename=tab_angled_border3@2x.png tab_angled_border3.svg
rem inkscape --export-type=png --export-dpi=288 --export-filename=tab_angled_border3@3x.png tab_angled_border3.svg
rem inkscape --export-type=png --export-dpi=96 --export-filename=tab_angled_shadow.png tab_angled_shadow.svg
rem inkscape --export-type=png --export-dpi=192 --export-filename=tab_angled_shadow@2x.png tab_angled_shadow.svg
rem inkscape --export-type=png --export-dpi=288 --export-filename=tab_angled_shadow@3x.png tab_angled_shadow.svg
rem inkscape --export-type=png --export-dpi=96 --export-filename=tab_angled_shadow2.png tab_angled_shadow2.svg
rem inkscape --export-type=png --export-dpi=192 --export-filename=tab_angled_shadow2@2x.png tab_angled_shadow2.svg
rem inkscape --export-type=png --export-dpi=288 --export-filename=tab_angled_shadow2@3x.png tab_angled_shadow2.svg
rem inkscape --export-type=png --export-dpi=96 --export-filename=tab_angled_shadow3.png tab_angled_shadow3.svg
rem inkscape --export-type=png --export-dpi=192 --export-filename=tab_angled_shadow3@2x.png tab_angled_shadow3.svg
rem inkscape --export-type=png --export-dpi=288 --export-filename=tab_angled_shadow3@3x.png tab_angled_shadow3.svg
rem inkscape --export-type=png --export-dpi=96 --export-filename=tab_angled_shadow4.png tab_angled_shadow4.svg
rem inkscape --export-type=png --export-dpi=192 --export-filename=tab_angled_shadow4@2x.png tab_angled_shadow4.svg
rem inkscape --export-type=png --export-dpi=288 --export-filename=tab_angled_shadow4@3x.png tab_angled_shadow4.svg
rem inkscape --export-type=png --export-dpi=96 --export-filename=tab_angled_highlight.png tab_angled_highlight.svg
rem inkscape --export-type=png --export-dpi=192 --export-filename=tab_angled_highlight@2x.png tab_angled_highlight.svg
rem inkscape --export-type=png --export-dpi=288 --export-filename=tab_angled_highlight@3x.png tab_angled_highlight.svg
rem inkscape --export-type=png --export-dpi=96 --export-filename=tab_angled_highlight2.png tab_angled_highlight2.svg
rem inkscape --export-type=png --export-dpi=192 --export-filename=tab_angled_highlight2@2x.png tab_angled_highlight2.svg
rem inkscape --export-type=png --export-dpi=288 --export-filename=tab_angled_highlight2@3x.png tab_angled_highlight2.svg
rem inkscape --export-type=png --export-dpi=96 --export-filename=tab_angled_highlight3.png tab_angled_highlight3.svg
rem inkscape --export-type=png --export-dpi=192 --export-filename=tab_angled_highlight3@2x.png tab_angled_highlight3.svg
rem inkscape --export-type=png --export-dpi=288 --export-filename=tab_angled_highlight3@3x.png tab_angled_highlight3.svg
rem inkscape --export-type=png --export-dpi=96 --export-filename=tab_angled_highlight4.png tab_angled_highlight4.svg
rem inkscape --export-type=png --export-dpi=192 --export-filename=tab_angled_highlight4@2x.png tab_angled_highlight4.svg
rem inkscape --export-type=png --export-dpi=288 --export-filename=tab_angled_highlight4@3x.png tab_angled_highlight4.svg
rem inkscape --export-type=png --export-dpi=96 --export-filename=tab_angled_highlight5.png tab_angled_highlight5.svg
rem inkscape --export-type=png --export-dpi=192 --export-filename=tab_angled_highlight5@2x.png tab_angled_highlight5.svg
rem inkscape --export-type=png --export-dpi=288 --export-filename=tab_angled_highlight5@3x.png tab_angled_highlight5.svg
rem inkscape --export-type=png --export-dpi=96 --export-filename=tab_angled_highlight6.png tab_angled_highlight6.svg
rem inkscape --export-type=png --export-dpi=192 --export-filename=tab_angled_highlight6@2x.png tab_angled_highlight6.svg
rem inkscape --export-type=png --export-dpi=288 --export-filename=tab_angled_highlight6@3x.png tab_angled_highlight6.svg
rem inkscape --export-type=png --export-dpi=96 --export-filename=tab_angled_highlight7.png tab_angled_highlight7.svg
rem inkscape --export-type=png --export-dpi=192 --export-filename=tab_angled_highlight7@2x.png tab_angled_highlight7.svg
rem inkscape --export-type=png --export-dpi=288 --export-filename=tab_angled_highlight7@3x.png tab_angled_highlight7.svg
rem inkscape --export-type=png --export-dpi=96 --export-filename=tab_angled_highlight8.png tab_angled_highlight8.svg
rem inkscape --export-type=png --export-dpi=192 --export-filename=tab_angled_highlight8@2x.png tab_angled_highlight8.svg
rem inkscape --export-type=png --export-dpi=288 --export-filename=tab_angled_highlight8@3x.png tab_angled_highlight8.svg
rem inkscape --export-type=png --export-dpi=96 --export-filename=tab_angled_divider.png tab_angled_divider.svg
rem inkscape --export-type=png --export-dpi=192 --export-filename=tab_angled_divider@2x.png tab_angled_divider.svg
rem inkscape --export-type=png --export-dpi=288 --export-filename=tab_angled_divider@3x.png tab_angled_divider.svg
rem inkscape --export-type=png --export-dpi=96 --export-filename=tab_wave.png tab_wave.svg
rem inkscape --export-type=png --export-dpi=192 --export-filename=tab_wave@2x.png tab_wave.svg
rem inkscape --export-type=png --export-dpi=288 --export-filename=tab_wave@3x.png tab_wave.svg
rem inkscape --export-type=png --export-dpi=96 --export-filename=tab_wave_border.png tab_wave_border.svg
rem inkscape --export-type=png --export-dpi=192 --export-filename=tab_wave_border@2x.png tab_wave_border.svg
rem inkscape --export-type=png --export-dpi=288 --export-filename=tab_wave_border@3x.png tab_wave_border.svg
rem inkscape --export-type=png --export-dpi=96 --export-filename=tab_wave_border2.png tab_wave_border2.svg
rem inkscape --export-type=png --export-dpi=192 --export-filename=tab_wave_border2@2x.png tab_wave_border2.svg
rem inkscape --export-type=png --export-dpi=288 --export-filename=tab_wave_border2@3x.png tab_wave_border2.svg
rem inkscape --export-type=png --export-dpi=96 --export-filename=tab_wave_shadow.png tab_wave_shadow.svg
rem inkscape --export-type=png --export-dpi=192 --export-filename=tab_wave_shadow@2x.png tab_wave_shadow.svg
rem inkscape --export-type=png --export-dpi=288 --export-filename=tab_wave_shadow@3x.png tab_wave_shadow.svg
rem inkscape --export-type=png --export-dpi=96 --export-filename=tab_wave_shadow2.png tab_wave_shadow2.svg
rem inkscape --export-type=png --export-dpi=192 --export-filename=tab_wave_shadow2@2x.png tab_wave_shadow2.svg
rem inkscape --export-type=png --export-dpi=288 --export-filename=tab_wave_shadow2@3x.png tab_wave_shadow2.svg
rem inkscape --export-type=png --export-dpi=96 --export-filename=tab_wave_highlight.png tab_wave_highlight.svg
rem inkscape --export-type=png --export-dpi=192 --export-filename=tab_wave_highlight@2x.png tab_wave_highlight.svg
rem inkscape --export-type=png --export-dpi=288 --export-filename=tab_wave_highlight@3x.png tab_wave_highlight.svg
rem inkscape --export-type=png --export-dpi=96 --export-filename=tab_wave_highlight2.png tab_wave_highlight2.svg
rem inkscape --export-type=png --export-dpi=192 --export-filename=tab_wave_highlight2@2x.png tab_wave_highlight2.svg
rem inkscape --export-type=png --export-dpi=288 --export-filename=tab_wave_highlight2@3x.png tab_wave_highlight2.svg
rem inkscape --export-type=png --export-dpi=96 --export-filename=tab_wave_highlight3.png tab_wave_highlight3.svg
rem inkscape --export-type=png --export-dpi=192 --export-filename=tab_wave_highlight3@2x.png tab_wave_highlight3.svg
rem inkscape --export-type=png --export-dpi=288 --export-filename=tab_wave_highlight3@3x.png tab_wave_highlight3.svg
rem inkscape --export-type=png --export-dpi=96 --export-filename=tab_wave_highlight4.png tab_wave_highlight4.svg
rem inkscape --export-type=png --export-dpi=192 --export-filename=tab_wave_highlight4@2x.png tab_wave_highlight4.svg
rem inkscape --export-type=png --export-dpi=288 --export-filename=tab_wave_highlight4@3x.png tab_wave_highlight4.svg
rem inkscape --export-type=png --export-dpi=96 --export-filename=tab_wave_highlight5.png tab_wave_highlight5.svg
rem inkscape --export-type=png --export-dpi=192 --export-filename=tab_wave_highlight5@2x.png tab_wave_highlight5.svg
rem inkscape --export-type=png --export-dpi=288 --export-filename=tab_wave_highlight5@3x.png tab_wave_highlight5.svg
rem inkscape --export-type=png --export-dpi=96 --export-filename=tab_wave_highlight6.png tab_wave_highlight6.svg
rem inkscape --export-type=png --export-dpi=192 --export-filename=tab_wave_highlight6@2x.png tab_wave_highlight6.svg
rem inkscape --export-type=png --export-dpi=288 --export-filename=tab_wave_highlight6@3x.png tab_wave_highlight6.svg
rem inkscape --export-type=png --export-dpi=96 --export-filename=tab_wave_highlight7.png tab_wave_highlight7.svg
rem inkscape --export-type=png --export-dpi=192 --export-filename=tab_wave_highlight7@2x.png tab_wave_highlight7.svg
rem inkscape --export-type=png --export-dpi=288 --export-filename=tab_wave_highlight7@3x.png tab_wave_highlight7.svg
rem inkscape --export-type=png --export-dpi=96 --export-filename=tab_wave_highlight8.png tab_wave_highlight8.svg
rem inkscape --export-type=png --export-dpi=192 --export-filename=tab_wave_highlight8@2x.png tab_wave_highlight8.svg
rem inkscape --export-type=png --export-dpi=288 --export-filename=tab_wave_highlight8@3x.png tab_wave_highlight8.svg
rem inkscape --export-type=png --export-dpi=96 --export-filename=tab_wave_divider.png tab_wave_divider.svg
rem inkscape --export-type=png --export-dpi=192 --export-filename=tab_wave_divider@2x.png tab_wave_divider.svg
rem inkscape --export-type=png --export-dpi=288 --export-filename=tab_wave_divider@3x.png tab_wave_divider.svg
