inkscape --export-type=png -w 15 -h 15 --export-filename=status_added.png status_added.svg
inkscape --export-type=png -w 30 -h 30 --export-filename=status_added@2x.png status_added.svg
inkscape --export-type=png -w 45 -h 45 --export-filename=status_added@3x.png status_added.svg
inkscape --export-type=png -w 15 -h 15 --export-filename=status_deleted.png status_deleted.svg
inkscape --export-type=png -w 30 -h 30 --export-filename=status_deleted@2x.png status_deleted.svg
inkscape --export-type=png -w 45 -h 45 --export-filename=status_deleted@3x.png status_deleted.svg
inkscape --export-type=png -w 15 -h 15 --export-filename=status_ignored.png status_ignored.svg
inkscape --export-type=png -w 30 -h 30 --export-filename=status_ignored@2x.png status_ignored.svg
inkscape --export-type=png -w 45 -h 45 --export-filename=status_ignored@3x.png status_ignored.svg
inkscape --export-type=png -w 15 -h 15 --export-filename=status_missing.png status_missing.svg
inkscape --export-type=png -w 30 -h 30 --export-filename=status_missing@2x.png status_missing.svg
inkscape --export-type=png -w 45 -h 45 --export-filename=status_missing@3x.png status_missing.svg
inkscape --export-type=png -w 15 -h 15 --export-filename=status_modified.png status_modified.svg
inkscape --export-type=png -w 30 -h 30 --export-filename=status_modified@2x.png status_modified.svg
inkscape --export-type=png -w 45 -h 45 --export-filename=status_modified@3x.png status_modified.svg
inkscape --export-type=png -w 15 -h 15 --export-filename=status_staged.png status_staged.svg
inkscape --export-type=png -w 30 -h 30 --export-filename=status_staged@2x.png status_staged.svg
inkscape --export-type=png -w 45 -h 45 --export-filename=status_staged@3x.png status_staged.svg
inkscape --export-type=png -w 15 -h 15 --export-filename=status_unmerged.png status_unmerged.svg
inkscape --export-type=png -w 30 -h 30 --export-filename=status_unmerged@2x.png status_unmerged.svg
inkscape --export-type=png -w 45 -h 45 --export-filename=status_unmerged@3x.png status_unmerged.svg
inkscape --export-type=png -w 15 -h 15 --export-filename=status_untracked.png status_untracked.svg
inkscape --export-type=png -w 30 -h 30 --export-filename=status_untracked@2x.png status_untracked.svg
inkscape --export-type=png -w 45 -h 45 --export-filename=status_untracked@3x.png status_untracked.svg
