inkscape --export-type=png -w 16 -h 16 --export-filename=fold_closed.png fold_closed.svg
inkscape --export-type=png -w 32 -h 32 --export-filename=fold_closed@2x.png fold_closed.svg
inkscape --export-type=png -w 48 -h 48 --export-filename=fold_closed@3x.png fold_closed.svg
inkscape --export-type=png -w 16 -h 16 --export-filename=fold_opened.png fold_opened.svg
inkscape --export-type=png -w 32 -h 32 --export-filename=fold_opened@2x.png fold_opened.svg
inkscape --export-type=png -w 48 -h 48 --export-filename=fold_opened@3x.png fold_opened.svg
inkscape --export-type=png -w 16 -h 16 --export-filename=fold1.png fold1.svg
inkscape --export-type=png -w 32 -h 32 --export-filename=fold1@2x.png fold1.svg
inkscape --export-type=png -w 48 -h 48 --export-filename=fold1@3x.png fold1.svg
inkscape --export-type=png -w 16 -h 16 --export-filename=fold2.png fold2.svg
inkscape --export-type=png -w 32 -h 32 --export-filename=fold2@2x.png fold2.svg
inkscape --export-type=png -w 48 -h 48 --export-filename=fold2@3x.png fold2.svg
inkscape --export-type=png -w 16 -h 16 --export-filename=fold3.png fold3.svg
inkscape --export-type=png -w 32 -h 32 --export-filename=fold3@2x.png fold3.svg
inkscape --export-type=png -w 48 -h 48 --export-filename=fold3@3x.png fold3.svg
inkscape --export-type=png -w 16 -h 16 --export-filename=fold4.png fold4.svg
inkscape --export-type=png -w 32 -h 32 --export-filename=fold4@2x.png fold4.svg
inkscape --export-type=png -w 48 -h 48 --export-filename=fold4@3x.png fold4.svg
inkscape --export-type=png -w 16 -h 16 --export-filename=fold5.png fold5.svg
inkscape --export-type=png -w 32 -h 32 --export-filename=fold5@2x.png fold5.svg
inkscape --export-type=png -w 48 -h 48 --export-filename=fold5@3x.png fold5.svg
inkscape --export-type=png -w 16 -h 16 --export-filename=fold6.png fold6.svg
inkscape --export-type=png -w 32 -h 32 --export-filename=fold6@2x.png fold6.svg
inkscape --export-type=png -w 48 -h 48 --export-filename=fold6@3x.png fold6.svg
