rem inkscape --export-type=png -w 16 -h 16 --export-filename=annotation_close.png annotation_close.svg
rem inkscape --export-type=png -w 32 -h 32 --export-filename=annotation_close@2x.png annotation_close.svg
rem inkscape --export-type=png -w 48 -h 48 --export-filename=annotation_close@3x.png annotation_close.svg
rem inkscape --export-type=png -w 16 -h 16 --export-filename=branch.png branch.svg
rem inkscape --export-type=png -w 32 -h 32 --export-filename=branch@2x.png branch.svg
rem inkscape --export-type=png -w 48 -h 48 --export-filename=branch@3x.png branch.svg
rem inkscape --export-type=png -w 12 -h 12 --export-filename=close.png close.svg
rem inkscape --export-type=png -w 24 -h 24 --export-filename=close@2x.png close.svg
rem inkscape --export-type=png -w 36 -h 36 --export-filename=close@3x.png close.svg
rem inkscape --export-type=png -w 6 -h 14 --export-filename=scroll_thin.png scroll_thin.svg
rem inkscape --export-type=png -w 12 -h 28 --export-filename=scroll_thin@2x.png scroll_thin.svg
rem inkscape --export-type=png -w 18 -h 42 --export-filename=scroll_thin@3x.png scroll_thin.svg
rem inkscape --export-type=png -w 6 -h 14 --export-filename=scroll_thin2.png scroll_thin2.svg
rem inkscape --export-type=png -w 12 -h 28 --export-filename=scroll_thin2@2x.png scroll_thin2.svg
rem inkscape --export-type=png -w 18 -h 42 --export-filename=scroll_thin2@3x.png scroll_thin2.svg
rem inkscape --export-type=png -w 6 -h 14 --export-filename=scroll_thin3.png scroll_thin3.svg
rem inkscape --export-type=png -w 12 -h 28 --export-filename=scroll_thin3@2x.png scroll_thin3.svg
rem inkscape --export-type=png -w 18 -h 42 --export-filename=scroll_thin3@3x.png scroll_thin3.svg
rem inkscape --export-type=png -w 14 -h 6 --export-filename=scroll_horiz_thin.png scroll_horiz_thin.svg
rem inkscape --export-type=png -w 28 -h 12 --export-filename=scroll_horiz_thin@2x.png scroll_horiz_thin.svg
rem inkscape --export-type=png -w 42 -h 18 --export-filename=scroll_horiz_thin@3x.png scroll_horiz_thin.svg
rem inkscape --export-type=png -w 14 -h 6 --export-filename=scroll_horiz_thin2.png scroll_horiz_thin2.svg
rem inkscape --export-type=png -w 28 -h 12 --export-filename=scroll_horiz_thin2@2x.png scroll_horiz_thin2.svg
rem inkscape --export-type=png -w 42 -h 18 --export-filename=scroll_horiz_thin2@3x.png scroll_horiz_thin2.svg
rem inkscape --export-type=png -w 14 -h 6 --export-filename=scroll_horiz_thin3.png scroll_horiz_thin3.svg
rem inkscape --export-type=png -w 28 -h 12 --export-filename=scroll_horiz_thin3@2x.png scroll_horiz_thin3.svg
rem inkscape --export-type=png -w 42 -h 18 --export-filename=scroll_horiz_thin3@3x.png scroll_horiz_thin3.svg
rem inkscape --export-type=png -w 12 -h 39 --export-filename=sidebar_angled_background.png sidebar_angled_background.svg
rem inkscape --export-type=png -w 24 -h 78 --export-filename=sidebar_angled_background@2x.png sidebar_angled_background.svg
rem inkscape --export-type=png -w 36 -h 117 --export-filename=sidebar_angled_background@3x.png sidebar_angled_background.svg
rem inkscape --export-type=png -w 12 -h 39 --export-filename=sidebar_angled_border.png sidebar_angled_border.svg
rem inkscape --export-type=png -w 24 -h 78 --export-filename=sidebar_angled_border@2x.png sidebar_angled_border.svg
rem inkscape --export-type=png -w 36 -h 117 --export-filename=sidebar_angled_border@3x.png sidebar_angled_border.svg
rem inkscape --export-type=png -w 12 -h 39 --export-filename=sidebar_rounded_background.png sidebar_rounded_background.svg
rem inkscape --export-type=png -w 24 -h 78 --export-filename=sidebar_rounded_background@2x.png sidebar_rounded_background.svg
rem inkscape --export-type=png -w 36 -h 117 --export-filename=sidebar_rounded_background@3x.png sidebar_rounded_background.svg
rem inkscape --export-type=png -w 12 -h 39 --export-filename=sidebar_rounded_border.png sidebar_rounded_border.svg
rem inkscape --export-type=png -w 24 -h 78 --export-filename=sidebar_rounded_border@2x.png sidebar_rounded_border.svg
rem inkscape --export-type=png -w 36 -h 117 --export-filename=sidebar_rounded_border@3x.png sidebar_rounded_border.svg
rem inkscape --export-type=png -w 12 -h 39 --export-filename=sidebar_square_background.png sidebar_square_background.svg
rem inkscape --export-type=png -w 24 -h 78 --export-filename=sidebar_square_background@2x.png sidebar_square_background.svg
rem inkscape --export-type=png -w 36 -h 117 --export-filename=sidebar_square_background@3x.png sidebar_square_background.svg
rem inkscape --export-type=png -w 12 -h 39 --export-filename=sidebar_square_border.png sidebar_square_border.svg
rem inkscape --export-type=png -w 24 -h 78 --export-filename=sidebar_square_border@2x.png sidebar_square_border.svg
rem inkscape --export-type=png -w 36 -h 117 --export-filename=sidebar_square_border@3x.png sidebar_square_border.svg
rem inkscape --export-type=png -w 16 -h 16 --export-filename=sidebar_row_selected.png sidebar_row_selected.svg
rem inkscape --export-type=png -w 32 -h 32 --export-filename=sidebar_row_selected@2x.png sidebar_row_selected.svg
rem inkscape --export-type=png -w 48 -h 48 --export-filename=sidebar_row_selected@3x.png sidebar_row_selected.svg
rem inkscape --export-type=png -w 16 -h 16 --export-filename=sidebar_row_selected_border.png sidebar_row_selected_border.svg
rem inkscape --export-type=png -w 32 -h 32 --export-filename=sidebar_row_selected_border@2x.png sidebar_row_selected_border.svg
rem inkscape --export-type=png -w 48 -h 48 --export-filename=sidebar_row_selected_border@3x.png sidebar_row_selected_border.svg
rem inkscape --export-type=png -w 2 -h 34 --export-filename=tabset_border.png tabset_border.svg
rem inkscape --export-type=png -w 4 -h 68 --export-filename=tabset_border@2x.png tabset_border.svg
rem inkscape --export-type=png -w 6 -h 102 --export-filename=tabset_border@3x.png tabset_border.svg
rem inkscape --export-type=png -w 8 -h 34 --export-filename=tabset_shadow.png tabset_shadow.svg
rem inkscape --export-type=png -w 16 -h 68 --export-filename=tabset_shadow@2x.png tabset_shadow.svg
rem inkscape --export-type=png -w 24 -h 102 --export-filename=tabset_shadow@3x.png tabset_shadow.svg
rem inkscape --export-type=png -w 12 -h 12 --export-filename=tab_dirty.png tab_dirty.svg
rem inkscape --export-type=png -w 24 -h 24 --export-filename=tab_dirty@2x.png tab_dirty.svg
rem inkscape --export-type=png -w 36 -h 36 --export-filename=tab_dirty@3x.png tab_dirty.svg
rem inkscape --export-type=png -w 2 -h 34 --export-filename=tab_border_bottom.png tab_border_bottom.svg
rem inkscape --export-type=png -w 4 -h 68 --export-filename=tab_border_bottom@2x.png tab_border_bottom.svg
rem inkscape --export-type=png -w 6 -h 102 --export-filename=tab_border_bottom@3x.png tab_border_bottom.svg
rem inkscape --export-type=png -w 42 -h 34 --export-filename=tab_rounded.png tab_rounded.svg
rem inkscape --export-type=png -w 84 -h 68 --export-filename=tab_rounded@2x.png tab_rounded.svg
rem inkscape --export-type=png -w 126 -h 102 --export-filename=tab_rounded@3x.png tab_rounded.svg
rem inkscape --export-type=png -w 42 -h 34 --export-filename=tab_rounded_border.png tab_rounded_border.svg
rem inkscape --export-type=png -w 84 -h 68 --export-filename=tab_rounded_border@2x.png tab_rounded_border.svg
rem inkscape --export-type=png -w 126 -h 102 --export-filename=tab_rounded_border@3x.png tab_rounded_border.svg
rem inkscape --export-type=png -w 42 -h 34 --export-filename=tab_rounded_border2.png tab_rounded_border2.svg
rem inkscape --export-type=png -w 84 -h 68 --export-filename=tab_rounded_border2@2x.png tab_rounded_border2.svg
rem inkscape --export-type=png -w 126 -h 102 --export-filename=tab_rounded_border2@3x.png tab_rounded_border2.svg
rem inkscape --export-type=png -w 42 -h 34 --export-filename=tab_rounded_shadow.png tab_rounded_shadow.svg
rem inkscape --export-type=png -w 84 -h 68 --export-filename=tab_rounded_shadow@2x.png tab_rounded_shadow.svg
rem inkscape --export-type=png -w 126 -h 102 --export-filename=tab_rounded_shadow@3x.png tab_rounded_shadow.svg
rem inkscape --export-type=png -w 42 -h 34 --export-filename=tab_rounded_shadow2.png tab_rounded_shadow2.svg
rem inkscape --export-type=png -w 84 -h 68 --export-filename=tab_rounded_shadow2@2x.png tab_rounded_shadow2.svg
rem inkscape --export-type=png -w 126 -h 102 --export-filename=tab_rounded_shadow2@3x.png tab_rounded_shadow2.svg
rem inkscape --export-type=png -w 42 -h 34 --export-filename=tab_rounded_highlight.png tab_rounded_highlight.svg
rem inkscape --export-type=png -w 84 -h 68 --export-filename=tab_rounded_highlight@2x.png tab_rounded_highlight.svg
rem inkscape --export-type=png -w 126 -h 102 --export-filename=tab_rounded_highlight@3x.png tab_rounded_highlight.svg
rem inkscape --export-type=png -w 42 -h 34 --export-filename=tab_rounded_highlight2.png tab_rounded_highlight2.svg
rem inkscape --export-type=png -w 84 -h 68 --export-filename=tab_rounded_highlight2@2x.png tab_rounded_highlight2.svg
rem inkscape --export-type=png -w 126 -h 102 --export-filename=tab_rounded_highlight2@3x.png tab_rounded_highlight2.svg
rem inkscape --export-type=png -w 42 -h 34 --export-filename=tab_rounded_highlight3.png tab_rounded_highlight3.svg
rem inkscape --export-type=png -w 84 -h 68 --export-filename=tab_rounded_highlight3@2x.png tab_rounded_highlight3.svg
rem inkscape --export-type=png -w 126 -h 102 --export-filename=tab_rounded_highlight3@3x.png tab_rounded_highlight3.svg
rem inkscape --export-type=png -w 42 -h 34 --export-filename=tab_rounded_highlight4.png tab_rounded_highlight4.svg
rem inkscape --export-type=png -w 84 -h 68 --export-filename=tab_rounded_highlight4@2x.png tab_rounded_highlight4.svg
rem inkscape --export-type=png -w 126 -h 102 --export-filename=tab_rounded_highlight4@3x.png tab_rounded_highlight4.svg
rem inkscape --export-type=png -w 42 -h 34 --export-filename=tab_rounded_divider.png tab_rounded_divider.svg
rem inkscape --export-type=png -w 84 -h 68 --export-filename=tab_rounded_divider@2x.png tab_rounded_divider.svg
rem inkscape --export-type=png -w 126 -h 102 --export-filename=tab_rounded_divider@3x.png tab_rounded_divider.svg
rem inkscape --export-type=png -w 42 -h 34 --export-filename=tab_square.png tab_square.svg
rem inkscape --export-type=png -w 84 -h 68 --export-filename=tab_square@2x.png tab_square.svg
rem inkscape --export-type=png -w 126 -h 102 --export-filename=tab_square@3x.png tab_square.svg
rem inkscape --export-type=png -w 42 -h 34 --export-filename=tab_square2.png tab_square2.svg
rem inkscape --export-type=png -w 84 -h 68 --export-filename=tab_square2@2x.png tab_square2.svg
rem inkscape --export-type=png -w 126 -h 102 --export-filename=tab_square2@3x.png tab_square2.svg
rem inkscape --export-type=png -w 42 -h 34 --export-filename=tab_square_border.png tab_square_border.svg
rem inkscape --export-type=png -w 84 -h 68 --export-filename=tab_square_border@2x.png tab_square_border.svg
rem inkscape --export-type=png -w 126 -h 102 --export-filename=tab_square_border@3x.png tab_square_border.svg
rem inkscape --export-type=png -w 42 -h 34 --export-filename=tab_square_border2.png tab_square_border2.svg
rem inkscape --export-type=png -w 84 -h 68 --export-filename=tab_square_border2@2x.png tab_square_border2.svg
rem inkscape --export-type=png -w 126 -h 102 --export-filename=tab_square_border2@3x.png tab_square_border2.svg
rem inkscape --export-type=png -w 42 -h 34 --export-filename=tab_square_shadow.png tab_square_shadow.svg
rem inkscape --export-type=png -w 84 -h 68 --export-filename=tab_square_shadow@2x.png tab_square_shadow.svg
rem inkscape --export-type=png -w 126 -h 102 --export-filename=tab_square_shadow@3x.png tab_square_shadow.svg
rem inkscape --export-type=png -w 42 -h 34 --export-filename=tab_square_shadow2.png tab_square_shadow2.svg
rem inkscape --export-type=png -w 84 -h 68 --export-filename=tab_square_shadow2@2x.png tab_square_shadow2.svg
rem inkscape --export-type=png -w 126 -h 102 --export-filename=tab_square_shadow2@3x.png tab_square_shadow2.svg
rem inkscape --export-type=png -w 42 -h 34 --export-filename=tab_square_highlight.png tab_square_highlight.svg
rem inkscape --export-type=png -w 84 -h 68 --export-filename=tab_square_highlight@2x.png tab_square_highlight.svg
rem inkscape --export-type=png -w 126 -h 102 --export-filename=tab_square_highlight@3x.png tab_square_highlight.svg
rem inkscape --export-type=png -w 42 -h 34 --export-filename=tab_square_highlight2.png tab_square_highlight2.svg
rem inkscape --export-type=png -w 84 -h 68 --export-filename=tab_square_highlight2@2x.png tab_square_highlight2.svg
rem inkscape --export-type=png -w 126 -h 102 --export-filename=tab_square_highlight2@3x.png tab_square_highlight2.svg
rem inkscape --export-type=png -w 42 -h 34 --export-filename=tab_square_highlight3.png tab_square_highlight3.svg
rem inkscape --export-type=png -w 84 -h 68 --export-filename=tab_square_highlight3@2x.png tab_square_highlight3.svg
rem inkscape --export-type=png -w 126 -h 102 --export-filename=tab_square_highlight3@3x.png tab_square_highlight3.svg
rem inkscape --export-type=png -w 42 -h 34 --export-filename=tab_square_highlight4.png tab_square_highlight4.svg
rem inkscape --export-type=png -w 84 -h 68 --export-filename=tab_square_highlight4@2x.png tab_square_highlight4.svg
rem inkscape --export-type=png -w 126 -h 102 --export-filename=tab_square_highlight4@3x.png tab_square_highlight4.svg
rem inkscape --export-type=png -w 42 -h 34 --export-filename=tab_square_divider.png tab_square_divider.svg
rem inkscape --export-type=png -w 84 -h 68 --export-filename=tab_square_divider@2x.png tab_square_divider.svg
rem inkscape --export-type=png -w 126 -h 102 --export-filename=tab_square_divider@3x.png tab_square_divider.svg
rem inkscape --export-type=png -w 42 -h 34 --export-filename=tab_square_divider2.png tab_square_divider2.svg
rem inkscape --export-type=png -w 84 -h 68 --export-filename=tab_square_divider2@2x.png tab_square_divider2.svg
rem inkscape --export-type=png -w 126 -h 102 --export-filename=tab_square_divider2@3x.png tab_square_divider2.svg
rem inkscape --export-type=png -w 42 -h 34 --export-filename=tab_angled.png tab_angled.svg
rem inkscape --export-type=png -w 84 -h 68 --export-filename=tab_angled@2x.png tab_angled.svg
rem inkscape --export-type=png -w 126 -h 102 --export-filename=tab_angled@3x.png tab_angled.svg
rem inkscape --export-type=png -w 42 -h 34 --export-filename=tab_angled_border.png tab_angled_border.svg
rem inkscape --export-type=png -w 84 -h 68 --export-filename=tab_angled_border@2x.png tab_angled_border.svg
rem inkscape --export-type=png -w 126 -h 102 --export-filename=tab_angled_border@3x.png tab_angled_border.svg
rem inkscape --export-type=png -w 42 -h 34 --export-filename=tab_angled_border2.png tab_angled_border2.svg
rem inkscape --export-type=png -w 84 -h 68 --export-filename=tab_angled_border2@2x.png tab_angled_border2.svg
rem inkscape --export-type=png -w 126 -h 102 --export-filename=tab_angled_border2@3x.png tab_angled_border2.svg
rem inkscape --export-type=png -w 42 -h 34 --export-filename=tab_angled_shadow.png tab_angled_shadow.svg
rem inkscape --export-type=png -w 84 -h 68 --export-filename=tab_angled_shadow@2x.png tab_angled_shadow.svg
rem inkscape --export-type=png -w 126 -h 102 --export-filename=tab_angled_shadow@3x.png tab_angled_shadow.svg
rem inkscape --export-type=png -w 42 -h 34 --export-filename=tab_angled_shadow2.png tab_angled_shadow2.svg
rem inkscape --export-type=png -w 84 -h 68 --export-filename=tab_angled_shadow2@2x.png tab_angled_shadow2.svg
rem inkscape --export-type=png -w 126 -h 102 --export-filename=tab_angled_shadow2@3x.png tab_angled_shadow2.svg
rem inkscape --export-type=png -w 42 -h 34 --export-filename=tab_angled_highlight.png tab_angled_highlight.svg
rem inkscape --export-type=png -w 84 -h 68 --export-filename=tab_angled_highlight@2x.png tab_angled_highlight.svg
rem inkscape --export-type=png -w 126 -h 102 --export-filename=tab_angled_highlight@3x.png tab_angled_highlight.svg
rem inkscape --export-type=png -w 42 -h 34 --export-filename=tab_angled_highlight2.png tab_angled_highlight2.svg
rem inkscape --export-type=png -w 84 -h 68 --export-filename=tab_angled_highlight2@2x.png tab_angled_highlight2.svg
rem inkscape --export-type=png -w 126 -h 102 --export-filename=tab_angled_highlight2@3x.png tab_angled_highlight2.svg
rem inkscape --export-type=png -w 42 -h 34 --export-filename=tab_angled_highlight3.png tab_angled_highlight3.svg
rem inkscape --export-type=png -w 84 -h 68 --export-filename=tab_angled_highlight3@2x.png tab_angled_highlight3.svg
rem inkscape --export-type=png -w 126 -h 102 --export-filename=tab_angled_highlight3@3x.png tab_angled_highlight3.svg
rem inkscape --export-type=png -w 42 -h 34 --export-filename=tab_angled_highlight4.png tab_angled_highlight4.svg
rem inkscape --export-type=png -w 84 -h 68 --export-filename=tab_angled_highlight4@2x.png tab_angled_highlight4.svg
rem inkscape --export-type=png -w 126 -h 102 --export-filename=tab_angled_highlight4@3x.png tab_angled_highlight4.svg
rem inkscape --export-type=png -w 42 -h 34 --export-filename=tab_angled_highlight5.png tab_angled_highlight5.svg
rem inkscape --export-type=png -w 84 -h 68 --export-filename=tab_angled_highlight5@2x.png tab_angled_highlight5.svg
rem inkscape --export-type=png -w 126 -h 102 --export-filename=tab_angled_highlight5@3x.png tab_angled_highlight5.svg
rem inkscape --export-type=png -w 42 -h 34 --export-filename=tab_angled_highlight6.png tab_angled_highlight6.svg
rem inkscape --export-type=png -w 84 -h 68 --export-filename=tab_angled_highlight6@2x.png tab_angled_highlight6.svg
rem inkscape --export-type=png -w 126 -h 102 --export-filename=tab_angled_highlight6@3x.png tab_angled_highlight6.svg
rem inkscape --export-type=png -w 42 -h 34 --export-filename=tab_angled_highlight7.png tab_angled_highlight7.svg
rem inkscape --export-type=png -w 84 -h 68 --export-filename=tab_angled_highlight7@2x.png tab_angled_highlight7.svg
rem inkscape --export-type=png -w 126 -h 102 --export-filename=tab_angled_highlight7@3x.png tab_angled_highlight7.svg
rem inkscape --export-type=png -w 42 -h 34 --export-filename=tab_angled_highlight8.png tab_angled_highlight8.svg
rem inkscape --export-type=png -w 84 -h 68 --export-filename=tab_angled_highlight8@2x.png tab_angled_highlight8.svg
rem inkscape --export-type=png -w 126 -h 102 --export-filename=tab_angled_highlight8@3x.png tab_angled_highlight8.svg
rem inkscape --export-type=png -w 42 -h 34 --export-filename=tab_angled_divider.png tab_angled_divider.svg
rem inkscape --export-type=png -w 84 -h 68 --export-filename=tab_angled_divider@2x.png tab_angled_divider.svg
rem inkscape --export-type=png -w 126 -h 102 --export-filename=tab_angled_divider@3x.png tab_angled_divider.svg
rem inkscape --export-type=png -w 60 -h 34 --export-filename=tab_wave.png tab_wave.svg
rem inkscape --export-type=png -w 120 -h 68 --export-filename=tab_wave@2x.png tab_wave.svg
rem inkscape --export-type=png -w 180 -h 102 --export-filename=tab_wave@3x.png tab_wave.svg
rem inkscape --export-type=png -w 60 -h 34 --export-filename=tab_wave_border.png tab_wave_border.svg
rem inkscape --export-type=png -w 120 -h 68 --export-filename=tab_wave_border@2x.png tab_wave_border.svg
rem inkscape --export-type=png -w 180 -h 102 --export-filename=tab_wave_border@3x.png tab_wave_border.svg
rem inkscape --export-type=png -w 60 -h 34 --export-filename=tab_wave_border2.png tab_wave_border2.svg
rem inkscape --export-type=png -w 120 -h 68 --export-filename=tab_wave_border2@2x.png tab_wave_border2.svg
rem inkscape --export-type=png -w 180 -h 102 --export-filename=tab_wave_border2@3x.png tab_wave_border2.svg
rem inkscape --export-type=png -w 60 -h 34 --export-filename=tab_wave_shadow.png tab_wave_shadow.svg
rem inkscape --export-type=png -w 120 -h 68 --export-filename=tab_wave_shadow@2x.png tab_wave_shadow.svg
rem inkscape --export-type=png -w 180 -h 102 --export-filename=tab_wave_shadow@3x.png tab_wave_shadow.svg
rem inkscape --export-type=png -w 60 -h 34 --export-filename=tab_wave_shadow2.png tab_wave_shadow2.svg
rem inkscape --export-type=png -w 120 -h 68 --export-filename=tab_wave_shadow2@2x.png tab_wave_shadow2.svg
rem inkscape --export-type=png -w 180 -h 102 --export-filename=tab_wave_shadow2@3x.png tab_wave_shadow2.svg
rem inkscape --export-type=png -w 60 -h 34 --export-filename=tab_wave_highlight.png tab_wave_highlight.svg
rem inkscape --export-type=png -w 120 -h 68 --export-filename=tab_wave_highlight@2x.png tab_wave_highlight.svg
rem inkscape --export-type=png -w 180 -h 102 --export-filename=tab_wave_highlight@3x.png tab_wave_highlight.svg
rem inkscape --export-type=png -w 60 -h 34 --export-filename=tab_wave_highlight2.png tab_wave_highlight2.svg
rem inkscape --export-type=png -w 120 -h 68 --export-filename=tab_wave_highlight2@2x.png tab_wave_highlight2.svg
rem inkscape --export-type=png -w 180 -h 102 --export-filename=tab_wave_highlight2@3x.png tab_wave_highlight2.svg
rem inkscape --export-type=png -w 60 -h 34 --export-filename=tab_wave_highlight3.png tab_wave_highlight3.svg
rem inkscape --export-type=png -w 120 -h 68 --export-filename=tab_wave_highlight3@2x.png tab_wave_highlight3.svg
rem inkscape --export-type=png -w 180 -h 102 --export-filename=tab_wave_highlight3@3x.png tab_wave_highlight3.svg
rem inkscape --export-type=png -w 60 -h 34 --export-filename=tab_wave_highlight4.png tab_wave_highlight4.svg
rem inkscape --export-type=png -w 120 -h 68 --export-filename=tab_wave_highlight4@2x.png tab_wave_highlight4.svg
rem inkscape --export-type=png -w 180 -h 102 --export-filename=tab_wave_highlight4@3x.png tab_wave_highlight4.svg
rem inkscape --export-type=png -w 60 -h 34 --export-filename=tab_wave_highlight5.png tab_wave_highlight5.svg
rem inkscape --export-type=png -w 120 -h 68 --export-filename=tab_wave_highlight5@2x.png tab_wave_highlight5.svg
rem inkscape --export-type=png -w 180 -h 102 --export-filename=tab_wave_highlight5@3x.png tab_wave_highlight5.svg
rem inkscape --export-type=png -w 60 -h 34 --export-filename=tab_wave_highlight6.png tab_wave_highlight6.svg
rem inkscape --export-type=png -w 120 -h 68 --export-filename=tab_wave_highlight6@2x.png tab_wave_highlight6.svg
rem inkscape --export-type=png -w 180 -h 102 --export-filename=tab_wave_highlight6@3x.png tab_wave_highlight6.svg
rem inkscape --export-type=png -w 60 -h 34 --export-filename=tab_wave_highlight7.png tab_wave_highlight7.svg
rem inkscape --export-type=png -w 120 -h 68 --export-filename=tab_wave_highlight7@2x.png tab_wave_highlight7.svg
rem inkscape --export-type=png -w 180 -h 102 --export-filename=tab_wave_highlight7@3x.png tab_wave_highlight7.svg
rem inkscape --export-type=png -w 60 -h 34 --export-filename=tab_wave_highlight8.png tab_wave_highlight8.svg
rem inkscape --export-type=png -w 120 -h 68 --export-filename=tab_wave_highlight8@2x.png tab_wave_highlight8.svg
rem inkscape --export-type=png -w 180 -h 102 --export-filename=tab_wave_highlight8@3x.png tab_wave_highlight8.svg
rem inkscape --export-type=png -w 60 -h 34 --export-filename=tab_wave_divider.png tab_wave_divider.svg
rem inkscape --export-type=png -w 120 -h 68 --export-filename=tab_wave_divider@2x.png tab_wave_divider.svg
rem inkscape --export-type=png -w 180 -h 102 --export-filename=tab_wave_divider@3x.png tab_wave_divider.svg
