inkscape --export-type=png -w 16 -h 16 --export-filename=annotation_close.png annotation_close.svg
inkscape --export-type=png -w 32 -h 32 --export-filename=annotation_close@2x.png annotation_close.svg
inkscape --export-type=png -w 48 -h 48 --export-filename=annotation_close@3x.png annotation_close.svg
inkscape --export-type=png -w 16 -h 16 --export-filename=branch.png branch.svg
inkscape --export-type=png -w 32 -h 32 --export-filename=branch@2x.png branch.svg
inkscape --export-type=png -w 48 -h 48 --export-filename=branch@3x.png branch.svg
inkscape --export-type=png -w 12 -h 12 --export-filename=close.png close.svg
inkscape --export-type=png -w 24 -h 24 --export-filename=close@2x.png close.svg
inkscape --export-type=png -w 36 -h 36 --export-filename=close@3x.png close.svg
inkscape --export-type=png -w 6 -h 14 --export-filename=scroll_thin.png scroll_thin.svg
inkscape --export-type=png -w 12 -h 28 --export-filename=scroll_thin@2x.png scroll_thin.svg
inkscape --export-type=png -w 18 -h 42 --export-filename=scroll_thin@3x.png scroll_thin.svg
inkscape --export-type=png -w 6 -h 14 --export-filename=scroll_thin2.png scroll_thin2.svg
inkscape --export-type=png -w 12 -h 28 --export-filename=scroll_thin2@2x.png scroll_thin2.svg
inkscape --export-type=png -w 18 -h 42 --export-filename=scroll_thin2@3x.png scroll_thin2.svg
inkscape --export-type=png -w 6 -h 14 --export-filename=scroll_thin3.png scroll_thin3.svg
inkscape --export-type=png -w 12 -h 28 --export-filename=scroll_thin3@2x.png scroll_thin3.svg
inkscape --export-type=png -w 18 -h 42 --export-filename=scroll_thin3@3x.png scroll_thin3.svg
inkscape --export-type=png -w 14 -h 6 --export-filename=scroll_horiz_thin.png scroll_horiz_thin.svg
inkscape --export-type=png -w 28 -h 12 --export-filename=scroll_horiz_thin@2x.png scroll_horiz_thin.svg
inkscape --export-type=png -w 42 -h 18 --export-filename=scroll_horiz_thin@3x.png scroll_horiz_thin.svg
inkscape --export-type=png -w 14 -h 6 --export-filename=scroll_horiz_thin2.png scroll_horiz_thin2.svg
inkscape --export-type=png -w 28 -h 12 --export-filename=scroll_horiz_thin2@2x.png scroll_horiz_thin2.svg
inkscape --export-type=png -w 42 -h 18 --export-filename=scroll_horiz_thin2@3x.png scroll_horiz_thin2.svg
inkscape --export-type=png -w 14 -h 6 --export-filename=scroll_horiz_thin3.png scroll_horiz_thin3.svg
inkscape --export-type=png -w 28 -h 12 --export-filename=scroll_horiz_thin3@2x.png scroll_horiz_thin3.svg
inkscape --export-type=png -w 42 -h 18 --export-filename=scroll_horiz_thin3@3x.png scroll_horiz_thin3.svg
inkscape --export-type=png -w 12 -h 37 --export-filename=sidebar_background_angled.png sidebar_background_angled.svg
inkscape --export-type=png -w 24 -h 74 --export-filename=sidebar_background_angled@2x.png sidebar_background_angled.svg
inkscape --export-type=png -w 36 -h 111 --export-filename=sidebar_background_angled@3x.png sidebar_background_angled.svg
inkscape --export-type=png -w 12 -h 37 --export-filename=sidebar_background_rounded.png sidebar_background_rounded.svg
inkscape --export-type=png -w 24 -h 74 --export-filename=sidebar_background_rounded@2x.png sidebar_background_rounded.svg
inkscape --export-type=png -w 36 -h 111 --export-filename=sidebar_background_rounded@3x.png sidebar_background_rounded.svg
inkscape --export-type=png -w 12 -h 37 --export-filename=sidebar_background_square.png sidebar_background_square.svg
inkscape --export-type=png -w 24 -h 74 --export-filename=sidebar_background_square@2x.png sidebar_background_square.svg
inkscape --export-type=png -w 36 -h 111 --export-filename=sidebar_background_square@3x.png sidebar_background_square.svg
inkscape --export-type=png -w 16 -h 16 --export-filename=sidebar_row_selected.png sidebar_row_selected.svg
inkscape --export-type=png -w 32 -h 32 --export-filename=sidebar_row_selected@2x.png sidebar_row_selected.svg
inkscape --export-type=png -w 48 -h 48 --export-filename=sidebar_row_selected@3x.png sidebar_row_selected.svg
inkscape --export-type=png -w 16 -h 16 --export-filename=sidebar_row_selected_border.png sidebar_row_selected_border.svg
inkscape --export-type=png -w 32 -h 32 --export-filename=sidebar_row_selected_border@2x.png sidebar_row_selected_border.svg
inkscape --export-type=png -w 48 -h 48 --export-filename=sidebar_row_selected_border@3x.png sidebar_row_selected_border.svg
inkscape --export-type=png -w 12 -h 12 --export-filename=tab_dirty.png tab_dirty.svg
inkscape --export-type=png -w 24 -h 24 --export-filename=tab_dirty@2x.png tab_dirty.svg
inkscape --export-type=png -w 36 -h 36 --export-filename=tab_dirty@3x.png tab_dirty.svg
