inkscape --export-type=png --export-area=-5:-2:17:20 -w 22 -h 22 --export-filename=kind_function.png kind_function.svg
inkscape --export-type=png --export-area=-5:-2:17:20 -w 44 -h 44 --export-filename=kind_function@2x.png kind_function.svg
inkscape --export-type=png --export-area=-5:-2:17:20 -w 66 -h 66 --export-filename=kind_function@3x.png kind_function.svg
inkscape --export-type=png --export-area=-5:-2:17:20 -w 22 -h 22 --export-filename=kind_keyword.png kind_keyword.svg
inkscape --export-type=png --export-area=-5:-2:17:20 -w 44 -h 44 --export-filename=kind_keyword@2x.png kind_keyword.svg
inkscape --export-type=png --export-area=-5:-2:17:20 -w 66 -h 66 --export-filename=kind_keyword@3x.png kind_keyword.svg
inkscape --export-type=png --export-area=-5:-2:17:20 -w 22 -h 22 --export-filename=kind_markup.png kind_markup.svg
inkscape --export-type=png --export-area=-5:-2:17:20 -w 44 -h 44 --export-filename=kind_markup@2x.png kind_markup.svg
inkscape --export-type=png --export-area=-5:-2:17:20 -w 66 -h 66 --export-filename=kind_markup@3x.png kind_markup.svg
inkscape --export-type=png --export-area=-5:-2:17:20 -w 22 -h 22 --export-filename=kind_namespace.png kind_namespace.svg
inkscape --export-type=png --export-area=-5:-2:17:20 -w 44 -h 44 --export-filename=kind_namespace@2x.png kind_namespace.svg
inkscape --export-type=png --export-area=-5:-2:17:20 -w 66 -h 66 --export-filename=kind_namespace@3x.png kind_namespace.svg
inkscape --export-type=png --export-area=-5:-2:17:20 -w 22 -h 22 --export-filename=kind_navigation.png kind_navigation.svg
inkscape --export-type=png --export-area=-5:-2:17:20 -w 44 -h 44 --export-filename=kind_navigation@2x.png kind_navigation.svg
inkscape --export-type=png --export-area=-5:-2:17:20 -w 66 -h 66 --export-filename=kind_navigation@3x.png kind_navigation.svg
inkscape --export-type=png --export-area=-5:-2:17:20 -w 22 -h 22 --export-filename=kind_snippet.png kind_snippet.svg
inkscape --export-type=png --export-area=-5:-2:17:20 -w 44 -h 44 --export-filename=kind_snippet@2x.png kind_snippet.svg
inkscape --export-type=png --export-area=-5:-2:17:20 -w 66 -h 66 --export-filename=kind_snippet@3x.png kind_snippet.svg
inkscape --export-type=png --export-area=-5:-2:17:20 -w 22 -h 22 --export-filename=kind_type.png kind_type.svg
inkscape --export-type=png --export-area=-5:-2:17:20 -w 44 -h 44 --export-filename=kind_type@2x.png kind_type.svg
inkscape --export-type=png --export-area=-5:-2:17:20 -w 66 -h 66 --export-filename=kind_type@3x.png kind_type.svg
inkscape --export-type=png --export-area=-5:-2:17:20 -w 22 -h 22 --export-filename=kind_variable.png kind_variable.svg
inkscape --export-type=png --export-area=-5:-2:17:20 -w 44 -h 44 --export-filename=kind_variable@2x.png kind_variable.svg
inkscape --export-type=png --export-area=-5:-2:17:20 -w 66 -h 66 --export-filename=kind_variable@3x.png kind_variable.svg
